services:
  lxc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: squid
    restart: unless-stopped
    privileged: true
    tty: true
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./lxc-whitelist:/etc/squid/whitelist
