services:
  almalinux:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    container_name: almalinux
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./work:/root/work
